// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"time"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var (
	_ = time.Time{}
	_ = uuid.UUID{}
	_ = loom.CommandBase{}
)

type InvoicePaid struct {
	PaidAt time.Time `json:"paid_at"`
	Status string    `json:"status"`
}

func (*InvoicePaid) LoomEvent() string { return "InvoicePaid" }

type InvoiceRaised struct {
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
	Status      string    `json:"status"`
}

func (*InvoiceRaised) LoomEvent() string { return "InvoiceRaised" }

type OrderPlaced struct {
	Currency   string    `json:"currency"`
	CustomerId uuid.UUID `json:"customer_id"`
	TotalCents int64     `json:"total_cents"`
}

func (*OrderPlaced) LoomEvent() string { return "OrderPlaced" }

type MarkInvoicePaid struct {
	loom.CommandBase
}

func (*MarkInvoicePaid) LoomCommand() string { return "MarkInvoicePaid" }

type RaiseInvoice struct {
	loom.CommandBase

	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
}

func (*RaiseInvoice) LoomCommand() string { return "RaiseInvoice" }

type Invoice struct {
	AmountCents int64      `json:"amount_cents"`
	Currency    string     `json:"currency"`
	CustomerId  uuid.UUID  `json:"customer_id"`
	PaidAt      *time.Time `json:"paid_at"`
	Status      string     `json:"status"`
}

func (s *Invoice) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *InvoicePaid:
		vPaidAt := e.PaidAt
		s.PaidAt = &vPaidAt
		s.Status = e.Status
	case *InvoiceRaised:
		s.AmountCents = e.AmountCents
		s.Currency = e.Currency
		s.CustomerId = e.CustomerId
		s.Status = e.Status
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}
