// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"fmt"
	"time"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var (
	_ = fmt.Sprintf
	_ = time.Time{}
	_ = uuid.UUID{}
	_ = loom.CommandBase{}
)

type InvoicePaid struct {
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
	PaidAt      time.Time `json:"paid_at"`
	Status      string    `json:"status"`
}

func (*InvoicePaid) LoomEvent() string { return "InvoicePaid" }

type InvoiceRaised struct {
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
	Status      string    `json:"status"`
}

func (*InvoiceRaised) LoomEvent() string { return "InvoiceRaised" }

type LedgerEntryPosted struct {
	AmountCents int64  `json:"amount_cents"`
	Currency    string `json:"currency"`
}

func (*LedgerEntryPosted) LoomEvent() string { return "LedgerEntryPosted" }

type OrderPlaced struct {
	Currency   string    `json:"currency"`
	CustomerId uuid.UUID `json:"customer_id"`
	TotalCents int64     `json:"total_cents"`
}

func (*OrderPlaced) LoomEvent() string { return "OrderPlaced" }

type PayeeRegistered struct {
	Name     string `json:"name"`
	Tin      string `json:"tin"`
	TinLast4 string `json:"tin_last4"`
}

func (*PayeeRegistered) LoomEvent() string { return "PayeeRegistered" }

type MarkInvoicePaid struct {
	loom.CommandBase
}

func (*MarkInvoicePaid) LoomCommand() string { return "MarkInvoicePaid" }

type RaiseInvoice struct {
	loom.CommandBase

	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
}

func (*RaiseInvoice) LoomCommand() string { return "RaiseInvoice" }

type RegisterPayee struct {
	loom.CommandBase

	Name     string `json:"name"`
	Tin      string `json:"tin"`
	TinLast4 string `json:"tin_last4"`
}

func (*RegisterPayee) LoomCommand() string { return "RegisterPayee" }

type PostLedgerEntry struct {
	loom.CommandBase

	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
}

func (*PostLedgerEntry) LoomCommand() string { return "PostLedgerEntry" }

type Invoice struct {
	AmountCents int64      `json:"amount_cents"`
	Currency    string     `json:"currency"`
	CustomerId  uuid.UUID  `json:"customer_id"`
	PaidAt      *time.Time `json:"paid_at"`
	Status      string     `json:"status"`
}

func (s *Invoice) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *InvoicePaid:
		s.AmountCents = e.AmountCents
		s.Currency = e.Currency
		s.CustomerId = e.CustomerId
		vPaidAt := e.PaidAt
		s.PaidAt = &vPaidAt
		s.Status = e.Status
	case *InvoiceRaised:
		s.AmountCents = e.AmountCents
		s.Currency = e.Currency
		s.CustomerId = e.CustomerId
		s.Status = e.Status
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}

type Payee struct {
	Name     string `json:"name"`
	Tin      string `json:"tin"`
	TinLast4 string `json:"tin_last4"`
}

func (s *Payee) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *PayeeRegistered:
		s.Name = e.Name
		s.Tin = e.Tin
		s.TinLast4 = e.TinLast4
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}

type LedgerEntry struct {
	AmountCents int64     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	CustomerId  uuid.UUID `json:"customer_id"`
	PostedAt    time.Time `json:"posted_at"`
}

type InvoiceSummary struct {
	AmountCents int64     `json:"amount_cents"`
	CustomerId  uuid.UUID `json:"customer_id"`
	Status      string    `json:"status"`
}

func (s *InvoiceSummary) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *InvoicePaid:
		s.AmountCents = e.AmountCents
		s.CustomerId = e.CustomerId
		s.Status = e.Status
	case *InvoiceRaised:
		s.AmountCents = e.AmountCents
		s.CustomerId = e.CustomerId
		s.Status = e.Status
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}

type PayeeDirectory struct {
	Name     string `json:"name"`
	Tin      string `json:"tin"`
	TinLast4 string `json:"tin_last4"`
}

func (s *PayeeDirectory) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *PayeeRegistered:
		s.Name = e.Name
		s.Tin = e.Tin
		s.TinLast4 = e.TinLast4
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}
