// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"context"
	"fmt"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var _ = uuid.UUID{}

func loomErrNilEvent(eventType string) error {
	return fmt.Errorf("nil payload for event %s", eventType)
}

type InvoiceHandlers interface {
	MarkInvoicePaid(ctx context.Context, state *Invoice, cmd *MarkInvoicePaid) ([]loom.DomainEvent, error)
	RaiseInvoice(ctx context.Context, state *Invoice, cmd *RaiseInvoice) ([]loom.DomainEvent, error)
}

type PayeeHandlers interface {
	RegisterPayee(ctx context.Context, state *Payee, cmd *RegisterPayee) ([]loom.DomainEvent, error)
}

type LedgerEntryHandlers interface {
	PostLedgerEntry(ctx context.Context, state *LedgerEntry, cmd *PostLedgerEntry) ([]loom.DomainEvent, error)
}

type PostLedgerReactions interface {
	OnInvoicePaid(ctx context.Context, evt *loom.Event, data *InvoicePaid) ([]loom.Command, error)
}

type CaptureOnPaidReactions interface {
	OnInvoicePaid(ctx context.Context, evt *loom.Event, data *InvoicePaid) ([]loom.Command, error)
}

type RaiseOnOrderReactions interface {
	OnOrderPlaced(ctx context.Context, evt *loom.Event, data *OrderPlaced) ([]loom.Command, error)
}

type Impl struct {
	Invoice       InvoiceHandlers
	Payee         PayeeHandlers
	LedgerEntry   LedgerEntryHandlers
	PostLedger    PostLedgerReactions
	CaptureOnPaid CaptureOnPaidReactions
	RaiseOnOrder  RaiseOnOrderReactions
}

func NewRegistry(impl Impl) *loom.Registry {
	return &loom.Registry{
		Service: "billing",
		Aggregates: []*loom.AggregateDef{
			{
				Name:          "Invoice",
				SnapshotEvery: 0,
				NewState:      func() loom.AggregateState { return &Invoice{} },
				Commands: []*loom.CommandDef{
					{
						Name:  "MarkInvoicePaid",
						New:   func() loom.Command { return &MarkInvoicePaid{} },
						Emits: []string{"InvoicePaid"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Invoice.MarkInvoicePaid(ctx, state.(*Invoice), cmd.(*MarkInvoicePaid))
							return asAny(evts), err
						},
					},
					{
						Name:  "RaiseInvoice",
						New:   func() loom.Command { return &RaiseInvoice{} },
						Emits: []string{"InvoiceRaised"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Invoice.RaiseInvoice(ctx, state.(*Invoice), cmd.(*RaiseInvoice))
							return asAny(evts), err
						},
					},
				},
			},
			{
				Name:          "Payee",
				SnapshotEvery: 1,
				StatePII:      []string{"tin"},
				NewState:      func() loom.AggregateState { return &Payee{} },
				Commands: []*loom.CommandDef{
					{
						Name:  "RegisterPayee",
						New:   func() loom.Command { return &RegisterPayee{} },
						Emits: []string{"PayeeRegistered"},
						PII:   []string{"tin"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Payee.RegisterPayee(ctx, state.(*Payee), cmd.(*RegisterPayee))
							return asAny(evts), err
						},
					},
				},
			},
		},
		Records: []*loom.RecordDef{
			{
				Name:     "LedgerEntry",
				NewState: func() any { return &LedgerEntry{} },
				Commands: []*loom.RecordCommandDef{
					{
						Name:  "PostLedgerEntry",
						New:   func() loom.Command { return &PostLedgerEntry{} },
						Emits: []string{"LedgerEntryPosted"},
						Handle: func(ctx context.Context, state any, cmd loom.Command) ([]any, error) {
							evts, err := impl.LedgerEntry.PostLedgerEntry(ctx, state.(*LedgerEntry), cmd.(*PostLedgerEntry))
							return asAny(evts), err
						},
					},
				},
			},
		},
		Events: []*loom.EventDef{
			{Name: "InvoicePaid", SchemaVersion: 1, Publish: true, Service: "", Aliases: nil, New: func() any { return &InvoicePaid{} }},
			{Name: "InvoiceRaised", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &InvoiceRaised{} }},
			{Name: "LedgerEntryPosted", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &LedgerEntryPosted{} }},
			{Name: "OrderPlaced", SchemaVersion: 1, Publish: true, Service: "orders", Aliases: nil, New: func() any { return &OrderPlaced{} }},
			{Name: "PayeeRegistered", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, PII: []string{"tin"}, New: func() any { return &PayeeRegistered{} }},
		},
		Policies: []*loom.ReactorDef{
			{
				Name:   "postLedger",
				Events: []string{"InvoicePaid"},
				Subs: []loom.SubscriptionDef{
					{Event: "InvoicePaid", Dispatches: []string{"PostLedgerEntry"}},
				},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *InvoicePaid:
						cmds, err := impl.PostLedger.OnInvoicePaid(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("postLedger", "InvoicePaid", []string{"PostLedgerEntry"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
		},
		Processes: []*loom.ReactorDef{
			{
				Name:   "captureOnPaid",
				Events: []string{"InvoicePaid"},
				Subs: []loom.SubscriptionDef{
					{Event: "InvoicePaid", Dispatches: nil},
				},
				Effects: []string{"gateway_capture"},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *InvoicePaid:
						cmds, err := impl.CaptureOnPaid.OnInvoicePaid(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("captureOnPaid", "InvoicePaid", nil, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
			{
				Name:   "raiseOnOrder",
				Events: []string{"OrderPlaced"},
				Subs: []loom.SubscriptionDef{
					{Event: "OrderPlaced", Dispatches: []string{"RaiseInvoice"}},
				},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *OrderPlaced:
						cmds, err := impl.RaiseOnOrder.OnOrderPlaced(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("raiseOnOrder", "OrderPlaced", []string{"RaiseInvoice"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
		},
		Projections: []*loom.ProjectionDef{
			{
				Name:     "payeeDirectory",
				Entity:   "PayeeDirectory",
				Events:   []string{"PayeeRegistered"},
				PII:      []string{"tin"},
				NewState: func() loom.EntityState { return &PayeeDirectory{} },
				EntityID: func(evt *loom.Event) uuid.UUID { return evt.AggregateID },
			},
		},
	}
}

func asAny[T any](in []T) []any {
	out := make([]any, len(in))
	for i, v := range in {
		out[i] = v
	}
	return out
}

func checkDispatches(reactor, event string, allowed []string, cmds []loom.Command) error {
	for _, cmd := range cmds {
		ok := false
		for _, a := range allowed {
			if cmd.LoomCommand() == a {
				ok = true
				break
			}
		}
		if !ok {
			return fmt.Errorf("%s on %s dispatched undeclared command %s", reactor, event, cmd.LoomCommand())
		}
	}
	return nil
}
