-- Code generated by loom generate. DO NOT EDIT.
--
-- Typed tables for @table entities/aggregates and series. Migrate
-- executes these and then applies an additive column diff; incompatible
-- drift is an error. @table remediation is drop table, Migrate, Rebuild;
-- series data is NOT rebuildable — incompatible series drift is migrated
-- by hand. On TimescaleDB, Migrate turns each series table into a
-- hypertable on its time column (with a retention policy for @retain);
-- on plain Postgres a @retain series is range-partitioned by day.

CREATE TABLE IF NOT EXISTS loom_t_billing_payee (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"name" text,
	"tin_last4" text,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);

