-- Code generated by loom generate. DO NOT EDIT.
--
-- Typed tables for @table entities and aggregates. Migrate executes
-- these and then applies an additive column diff; incompatible drift is
-- an error, and the remediation is drop table, Migrate, Rebuild.

CREATE TABLE IF NOT EXISTS loom_t_billing_payee (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"name" text,
	"tin_last4" text,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);

