package docs

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/go-apis/loom/schema"
)

func renderIndex(m *Model) string {
	var b strings.Builder
	b.WriteString("# System map\n\nGenerated by `loom docs` — do not edit.\n\n")
	b.WriteString("| service | aggregates | events | handlers |\n|---|---|---|---|\n")
	for _, s := range m.Schemas {
		fmt.Fprintf(&b, "| [%s](%s.md) | %d | %d | %d |\n", s.Service, s.Service, len(s.Aggregates), len(s.Events), len(s.Handlers))
	}
	b.WriteString("\nSee [topology](topology.md), the [event catalog](catalog.md), and the [drift report](drift.md).\n")
	return b.String()
}

func renderDrift(m *Model) string {
	var b strings.Builder
	b.WriteString("# Foreign-event drift report\n\n")
	b.WriteString("Every foreign-event redeclaration checked against the owning service's schema.\n\n")
	if len(m.Drift) == 0 {
		b.WriteString("No drift detected.\n")
		return b.String()
	}
	for _, d := range m.Drift {
		fmt.Fprintf(&b, "- ⚠️ %s\n", d)
	}
	return b.String()
}

func renderCatalog(m *Model) string {
	var b strings.Builder
	b.WriteString("# Event catalog\n\n")
	for _, s := range m.Schemas {
		for _, e := range s.Events {
			if e.Service != "" {
				continue // foreign declarations appear under their owner
			}
			fmt.Fprintf(&b, "## %s\n\n", e.Name)
			fmt.Fprintf(&b, "- **owner:** %s\n", s.Service)
			fmt.Fprintf(&b, "- **published to bus:** %v\n", e.Publish)
			if len(e.Aliases) > 0 {
				fmt.Fprintf(&b, "- **aliases:** %s\n", strings.Join(e.Aliases, ", "))
			}
			if emitters := m.Emitters[key(s.Service, e.Name)]; len(emitters) > 0 {
				fmt.Fprintf(&b, "- **emitted by:** %s\n", strings.Join(emitterNames(emitters), ", "))
			}
			if consumers := m.Consumers[key(s.Service, e.Name)]; len(consumers) > 0 {
				var list []string
				for _, c := range consumers {
					list = append(list, fmt.Sprintf("%s/%s (%s, %s)", c.Service, c.Handler.Name, c.Handler.Kind, c.Handler.Execution))
				}
				sort.Strings(list)
				fmt.Fprintf(&b, "- **consumed by:** %s\n", strings.Join(list, "; "))
			}
			b.WriteString(renderPayload(e.Payload))
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderPayload(p *schema.Payload) string {
	if p == nil || len(p.Properties) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\n| field | type | required |\n|---|---|---|\n")
	required := map[string]bool{}
	for _, r := range p.Required {
		required[r] = true
	}
	var names []string
	for name := range p.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", name, payloadType(p.Properties[name]), boolMark(required[name]))
	}
	return b.String()
}

func payloadType(p *schema.Payload) string {
	if p == nil {
		return "any"
	}
	t := p.Type
	if t == "" {
		t = "any"
	}
	if p.Format != "" {
		t += " (" + p.Format + ")"
	}
	if p.Type == "array" {
		t = "array of " + payloadType(p.Items)
	}
	if p.Nullable {
		t += ", nullable"
	}
	return t
}

func boolMark(v bool) string {
	if v {
		return "yes"
	}
	return ""
}

func renderService(m *Model, s *schema.Schema) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", s.Service)

	if len(s.Aggregates) > 0 {
		b.WriteString("## Aggregates\n\n| aggregate | kind | snapshot | project |\n|---|---|---|---|\n")
		for _, a := range s.Aggregates {
			snapshot := ""
			if a.Snapshot != nil {
				snapshot = fmt.Sprintf("every=%d", a.Snapshot.Every)
				if a.Snapshot.Revision != "" {
					snapshot += " " + a.Snapshot.Revision
				}
			}
			project := "yes"
			if a.Project != nil && !*a.Project {
				project = "no"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", a.Name, a.Kind, snapshot, project)
		}
		b.WriteString("\n")

		for _, a := range s.Aggregates {
			if len(a.Commands) == 0 {
				continue
			}
			fmt.Fprintf(&b, "### %s commands\n\n| command | emits |\n|---|---|\n", a.Name)
			for _, c := range a.Commands {
				fmt.Fprintf(&b, "| %s | %s |\n", c.Name, strings.Join(c.Emits, ", "))
			}
			b.WriteString("\n")
		}
	}

	if len(s.Handlers) > 0 {
		b.WriteString("## Handlers\n\n| handler | kind | group | execution | chunked | subscribes / handles | dispatches | projects |\n|---|---|---|---|---|---|---|---|\n")
		for _, h := range s.Handlers {
			var subs, dispatches []string
			for _, sub := range h.Subscribes {
				subs = append(subs, sub.Event)
				dispatches = append(dispatches, sub.Dispatches...)
			}
			for _, c := range h.Commands {
				subs = append(subs, c.Name)
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s |\n",
				h.Name, h.Kind, h.Group, h.Execution, boolMark(h.Chunked),
				strings.Join(subs, ", "), strings.Join(uniqueSorted(dispatches), ", "), strings.Join(h.Projects, ", "))
		}
		b.WriteString("\n")
	}

	var own, foreign []*schema.Event
	for _, e := range s.Events {
		if e.Service == "" {
			own = append(own, e)
		} else {
			foreign = append(foreign, e)
		}
	}
	if len(own) > 0 {
		b.WriteString("## Events\n\n| event | published | emitted by | consumers |\n|---|---|---|---|\n")
		for _, e := range own {
			var consumers []string
			for _, c := range m.Consumers[key(s.Service, e.Name)] {
				consumers = append(consumers, c.Service+"/"+c.Handler.Name)
			}
			sort.Strings(consumers)
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", e.Name, boolMark(e.Publish),
				strings.Join(emitterNames(m.Emitters[key(s.Service, e.Name)]), ", "), strings.Join(consumers, ", "))
		}
		b.WriteString("\n")
	}
	if len(foreign) > 0 {
		b.WriteString("## Consumed foreign events\n\n| event | from |\n|---|---|\n")
		for _, e := range foreign {
			fmt.Fprintf(&b, "| %s | %s |\n", e.Name, e.Service)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Flow\n\n")
	b.WriteString(mermaid(m, []*schema.Schema{s}))
	return b.String()
}

func renderTopology(m *Model) string {
	var b strings.Builder
	b.WriteString("# Cross-service topology\n\n")
	b.WriteString("Aggregates `[(name)]`, handlers `[name]`, bus events `{{name}}`. Edge labels are events (aggregate→handler) and commands (handler→aggregate).\n\n")
	b.WriteString(mermaid(m, m.Schemas))
	return b.String()
}

var idClean = regexp.MustCompile(`[^a-zA-Z0-9_]`)

func nodeID(service, kind, name string) string {
	return idClean.ReplaceAllString(service+"_"+kind+"_"+name, "_")
}

// mermaid renders the flow graph for the given subset of services. Edges to
// events owned by services outside the subset go through bus nodes; internal
// (in-transaction) consumption connects directly.
func mermaid(m *Model, subset []*schema.Schema) string {
	inSubset := map[string]bool{}
	for _, s := range subset {
		inSubset[s.Service] = true
	}

	var b strings.Builder
	b.WriteString("```mermaid\nflowchart LR\n")

	type edge struct{ from, label, to string }
	var edges []edge
	busNodes := map[string]string{} // node id -> label

	for _, s := range subset {
		fmt.Fprintf(&b, "  subgraph %s\n", s.Service)
		for _, a := range s.Aggregates {
			fmt.Fprintf(&b, "    %s[(%s)]\n", nodeID(s.Service, "agg", a.Name), a.Name)
		}
		for _, h := range s.Handlers {
			label := h.Name
			if h.Chunked {
				label += " ⛓"
			}
			shape := "[%s]"
			if h.Execution == "in-transaction" {
				shape = "([%s])"
			}
			fmt.Fprintf(&b, "    %s"+shape+"\n", nodeID(s.Service, "h", h.Name), label)
		}
		b.WriteString("  end\n")
	}

	// aggregate --event--> consumers (direct when in-tx and same service,
	// via a bus node when published across the bus)
	for _, s := range subset {
		for _, e := range s.Events {
			owner := ownerOf(s, e)
			if owner != s.Service {
				continue // rendered from the owner's side (or via bus below)
			}
			k := key(owner, e.Name)
			consumers := m.Consumers[k]
			if len(consumers) == 0 {
				continue
			}
			emitters := m.Emitters[k]
			for _, c := range consumers {
				toNode := nodeID(c.Service, "h", c.Handler.Name)
				if !inSubset[c.Service] {
					continue
				}
				crossesBus := c.Service != owner || c.Handler.Execution == "async"
				if crossesBus && e.Publish {
					busID := nodeID(owner, "bus", e.Name)
					busNodes[busID] = e.Name
					for _, em := range emitters {
						edges = append(edges, edge{emitterNodeID(em), "", busID})
					}
					edges = append(edges, edge{busID, "", toNode})
				} else {
					for _, em := range emitters {
						edges = append(edges, edge{emitterNodeID(em), e.Name, toNode})
					}
				}
			}
		}
	}

	// handler --command--> aggregate
	for _, s := range subset {
		for _, h := range s.Handlers {
			from := nodeID(s.Service, "h", h.Name)
			for _, sub := range h.Subscribes {
				for _, cmd := range sub.Dispatches {
					if target, ok := m.HandlerOf[key(s.Service, cmd)]; ok {
						edges = append(edges, edge{from, cmd, emitterNodeID(target)})
					}
				}
			}
			for _, p := range h.Projects {
				edges = append(edges, edge{from, "", nodeID(s.Service, "agg", p)})
			}
		}
	}

	var busIDs []string
	for id := range busNodes {
		busIDs = append(busIDs, id)
	}
	sort.Strings(busIDs)
	for _, id := range busIDs {
		fmt.Fprintf(&b, "  %s{{%s}}\n", id, busNodes[id])
	}

	seen := map[string]bool{}
	for _, e := range edges {
		var line string
		if e.label != "" {
			line = fmt.Sprintf("  %s -- %s --> %s\n", e.from, e.label, e.to)
		} else {
			line = fmt.Sprintf("  %s --> %s\n", e.from, e.to)
		}
		if seen[line] {
			continue
		}
		seen[line] = true
		b.WriteString(line)
	}

	b.WriteString("```\n")
	return b.String()
}

func emitterNodeID(em Emitter) string {
	if em.Kind == "handler" {
		return nodeID(em.Service, "h", em.Name)
	}
	return nodeID(em.Service, "agg", em.Name)
}

func emitterNames(emitters []Emitter) []string {
	var out []string
	for _, em := range emitters {
		out = append(out, em.Name)
	}
	sort.Strings(out)
	return out
}

func uniqueSorted(list []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, v := range list {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	sort.Strings(out)
	return out
}
