// Command loom is the schema-first tooling for the es library.
//
//	loom extract --dir <service module> --service <name> [--out <file>] [--compiled <file>]
//	loom compile --in <file.loom> --out <file.yaml>
//	loom docs    --schemas <dir> --out <dir>
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/go-apis/loom/docs"
	"github.com/go-apis/loom/extract"
	"github.com/go-apis/loom/sdl"
)

func main() {
	if len(os.Args) < 2 {
		usage()
	}
	var err error
	switch os.Args[1] {
	case "extract":
		err = runExtract(os.Args[2:])
	case "compile":
		err = runCompile(os.Args[2:])
	case "docs":
		err = runDocs(os.Args[2:])
	default:
		usage()
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "loom:", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: loom extract --dir <module> --service <name> [--out <file.loom>] [--compiled <file.yaml>]")
	fmt.Fprintln(os.Stderr, "       loom compile --in <file.loom> [--out <file.yaml>]")
	fmt.Fprintln(os.Stderr, "       loom docs --schemas <dir> --out <dir>")
	os.Exit(2)
}

func runExtract(args []string) error {
	fs := flag.NewFlagSet("extract", flag.ExitOnError)
	dir := fs.String("dir", ".", "service module directory")
	service := fs.String("service", "", "service name (default: directory name)")
	out := fs.String("out", "", "SDL output file (default: <service>.loom)")
	compiled := fs.String("compiled", "", "also write the compiled schema (YAML) here")
	if err := fs.Parse(args); err != nil {
		return err
	}
	abs, err := filepath.Abs(*dir)
	if err != nil {
		return err
	}
	if *service == "" {
		*service = filepath.Base(abs)
	}
	if *out == "" {
		*out = *service + ".loom"
	}

	res, err := extract.Service(abs, *service)
	if err != nil {
		return err
	}
	for _, w := range res.Warnings {
		fmt.Fprintf(os.Stderr, "warn: %s: %s\n", *service, w)
	}

	src := append([]byte("// Code generated by loom extract. DO NOT EDIT.\n"), sdl.Emit(res.Schema)...)
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		return err
	}
	if *compiled != "" {
		if err := res.Schema.WriteFile(*compiled); err != nil {
			return err
		}
	}
	fmt.Printf("%s: %d aggregates, %d events, %d handlers -> %s\n",
		*service, len(res.Schema.Aggregates), len(res.Schema.Events), len(res.Schema.Handlers), *out)
	return nil
}

func runCompile(args []string) error {
	fs := flag.NewFlagSet("compile", flag.ExitOnError)
	in := fs.String("in", "", "input .loom file")
	out := fs.String("out", "", "output file (default: <in>.yaml)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *in == "" {
		return fmt.Errorf("compile: --in is required")
	}
	if *out == "" {
		*out = *in + ".yaml"
	}
	src, err := os.ReadFile(*in)
	if err != nil {
		return err
	}
	s, err := sdl.Parse(string(src))
	if err != nil {
		return fmt.Errorf("%s: %w", *in, err)
	}
	if err := s.WriteFile(*out); err != nil {
		return err
	}
	fmt.Printf("%s -> %s\n", *in, *out)
	return nil
}

func runDocs(args []string) error {
	fs := flag.NewFlagSet("docs", flag.ExitOnError)
	schemas := fs.String("schemas", ".", "directory containing *.loom.yaml files")
	out := fs.String("out", "docs", "output directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	return docs.Generate(*schemas, *out)
}
