// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"time"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var (
	_ = time.Time{}
	_ = uuid.UUID{}
	_ = loom.CommandBase{}
)

type OrderItem struct {
	PriceCents int64  `json:"price_cents"`
	Quantity   int64  `json:"quantity"`
	Sku        string `json:"sku"`
}

type ContractAttached struct {
	Contract loom.FileRef `json:"contract"`
}

func (*ContractAttached) LoomEvent() string { return "ContractAttached" }

type ContractRequested struct {
	Requested loom.FileRef `json:"requested"`
}

func (*ContractRequested) LoomEvent() string { return "ContractRequested" }

type InvoicePaid struct {
	PaidAt time.Time `json:"paid_at"`
}

func (*InvoicePaid) LoomEvent() string { return "InvoicePaid" }

type OrderCancelled struct {
	Status string `json:"status"`
}

func (*OrderCancelled) LoomEvent() string { return "OrderCancelled" }

type OrderPlaced struct {
	Currency   string      `json:"currency"`
	CustomerId uuid.UUID   `json:"customer_id"`
	Items      []OrderItem `json:"items"`
	Status     string      `json:"status"`
	TotalCents int64       `json:"total_cents"`
}

func (*OrderPlaced) LoomEvent() string { return "OrderPlaced" }

type OrderShipped struct {
	ShippedAt time.Time `json:"shipped_at"`
	Status    string    `json:"status"`
}

func (*OrderShipped) LoomEvent() string { return "OrderShipped" }

type AttachContract struct {
	loom.CommandBase

	Contract loom.FileRef `json:"contract"`
}

func (*AttachContract) LoomCommand() string { return "AttachContract" }

type CancelOrder struct {
	loom.CommandBase
}

func (*CancelOrder) LoomCommand() string { return "CancelOrder" }

type PlaceOrder struct {
	loom.CommandBase

	Currency   string      `json:"currency"`
	CustomerId uuid.UUID   `json:"customer_id"`
	Items      []OrderItem `json:"items"`
}

func (*PlaceOrder) LoomCommand() string { return "PlaceOrder" }

type RequestContract struct {
	loom.CommandBase

	Contract loom.FileRef `json:"contract"`
}

func (*RequestContract) LoomCommand() string { return "RequestContract" }

type ShipOrder struct {
	loom.CommandBase
}

func (*ShipOrder) LoomCommand() string { return "ShipOrder" }

type Order struct {
	Contract   *loom.FileRef `json:"contract"`
	Currency   string        `json:"currency"`
	CustomerId uuid.UUID     `json:"customer_id"`
	Items      []OrderItem   `json:"items"`
	ShippedAt  *time.Time    `json:"shipped_at"`
	Status     string        `json:"status"`
	TotalCents int64         `json:"total_cents"`
}

func (s *Order) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *ContractAttached:
		vContract := e.Contract
		s.Contract = &vContract
	case *ContractRequested:
		_ = e // no shared fields
	case *OrderCancelled:
		s.Status = e.Status
	case *OrderPlaced:
		s.Currency = e.Currency
		s.CustomerId = e.CustomerId
		s.Items = e.Items
		s.Status = e.Status
		s.TotalCents = e.TotalCents
	case *OrderShipped:
		vShippedAt := e.ShippedAt
		s.ShippedAt = &vShippedAt
		s.Status = e.Status
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}

type CustomerSpend struct {
	OrderCount int64 `json:"order_count"`
	SpendCents int64 `json:"spend_cents"`
}

func (s *CustomerSpend) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *OrderPlaced:
		_ = e // no shared fields
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}

type OrderSummary struct {
	Currency   string    `json:"currency"`
	CustomerId uuid.UUID `json:"customer_id"`
	Status     string    `json:"status"`
	TotalCents int64     `json:"total_cents"`
}

func (s *OrderSummary) Fold(eventType string, data any) error {
	switch e := data.(type) {
	case *OrderCancelled:
		s.Status = e.Status
	case *OrderPlaced:
		s.Currency = e.Currency
		s.CustomerId = e.CustomerId
		s.Status = e.Status
		s.TotalCents = e.TotalCents
	case *OrderShipped:
		s.Status = e.Status
	case nil:
		_ = e
		return loomErrNilEvent(eventType)
	}
	return nil
}
