// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"context"
	"fmt"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var _ = uuid.UUID{}

func loomErrNilEvent(eventType string) error {
	return fmt.Errorf("nil payload for event %s", eventType)
}

type OrderHandlers interface {
	AttachContract(ctx context.Context, state *Order, cmd *AttachContract) ([]loom.DomainEvent, error)
	CancelOrder(ctx context.Context, state *Order, cmd *CancelOrder) ([]loom.DomainEvent, error)
	PlaceOrder(ctx context.Context, state *Order, cmd *PlaceOrder) ([]loom.DomainEvent, error)
	RequestContract(ctx context.Context, state *Order, cmd *RequestContract) ([]loom.DomainEvent, error)
	ShipOrder(ctx context.Context, state *Order, cmd *ShipOrder) ([]loom.DomainEvent, error)
}

type DropAutoCancelReactions interface {
	OnOrderShipped(ctx context.Context, evt *loom.Event, data *OrderShipped) ([]loom.Command, error)
}

type ScheduleAutoCancelReactions interface {
	OnOrderPlaced(ctx context.Context, evt *loom.Event, data *OrderPlaced) ([]loom.Command, error)
}

type ShipOnPaymentReactions interface {
	OnInvoicePaid(ctx context.Context, evt *loom.Event, data *InvoicePaid) ([]loom.Command, error)
}

type CustomerSpendFolds interface {
	OnOrderPlaced(state *CustomerSpend, evt *loom.Event, data *OrderPlaced) error
}

// EventUpcasts lifts stored payloads written under older @v versions:
// raw JSON of version n in, raw JSON of version n+1 out. Hops chain at
// decode time.
type EventUpcasts interface {
	OrderCancelledFromV1(data []byte) ([]byte, error)
}

type Impl struct {
	Order              OrderHandlers
	DropAutoCancel     DropAutoCancelReactions
	ScheduleAutoCancel ScheduleAutoCancelReactions
	ShipOnPayment      ShipOnPaymentReactions
	CustomerSpend      CustomerSpendFolds
	Upcasts            EventUpcasts
}

func NewRegistry(impl Impl) *loom.Registry {
	if impl.Upcasts == nil {
		panic("loomgen: the schema declares upcasts — wire Impl.Upcasts (see the Upcasts stub; your registry.go predates it)")
	}
	return &loom.Registry{
		Service: "orders",
		Aggregates: []*loom.AggregateDef{
			{
				Name:          "Order",
				SnapshotEvery: 5,
				NewState:      func() loom.AggregateState { return &Order{} },
				Commands: []*loom.CommandDef{
					{
						Name:  "AttachContract",
						New:   func() loom.Command { return &AttachContract{} },
						Emits: []string{"ContractAttached"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.AttachContract(ctx, state.(*Order), cmd.(*AttachContract))
							return asAny(evts), err
						},
					},
					{
						Name:  "CancelOrder",
						New:   func() loom.Command { return &CancelOrder{} },
						Emits: []string{"OrderCancelled"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.CancelOrder(ctx, state.(*Order), cmd.(*CancelOrder))
							return asAny(evts), err
						},
					},
					{
						Name:  "PlaceOrder",
						New:   func() loom.Command { return &PlaceOrder{} },
						Emits: []string{"OrderPlaced"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.PlaceOrder(ctx, state.(*Order), cmd.(*PlaceOrder))
							return asAny(evts), err
						},
					},
					{
						Name:  "RequestContract",
						New:   func() loom.Command { return &RequestContract{} },
						Emits: []string{"ContractRequested"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.RequestContract(ctx, state.(*Order), cmd.(*RequestContract))
							return asAny(evts), err
						},
					},
					{
						Name:  "ShipOrder",
						New:   func() loom.Command { return &ShipOrder{} },
						Emits: []string{"OrderShipped"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.ShipOrder(ctx, state.(*Order), cmd.(*ShipOrder))
							return asAny(evts), err
						},
					},
				},
			},
		},
		Records: []*loom.RecordDef{},
		Events: []*loom.EventDef{
			{Name: "ContractAttached", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &ContractAttached{} }},
			{Name: "ContractRequested", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &ContractRequested{} }},
			{Name: "InvoicePaid", SchemaVersion: 1, Publish: true, Service: "billing", Aliases: nil, New: func() any { return &InvoicePaid{} }},
			{Name: "OrderCancelled", SchemaVersion: 2, Publish: false, Service: "", Aliases: nil, Upcasts: map[int]loom.UpcastFunc{1: impl.Upcasts.OrderCancelledFromV1}, New: func() any { return &OrderCancelled{} }},
			{Name: "OrderPlaced", SchemaVersion: 1, Publish: true, Service: "", Aliases: nil, New: func() any { return &OrderPlaced{} }},
			{Name: "OrderShipped", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &OrderShipped{} }},
		},
		Policies: []*loom.ReactorDef{
			{
				Name:   "dropAutoCancel",
				Events: []string{"OrderShipped"},
				Subs: []loom.SubscriptionDef{
					{Event: "OrderShipped", Dispatches: []string{"CancelOrder"}},
				},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *OrderShipped:
						cmds, err := impl.DropAutoCancel.OnOrderShipped(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("dropAutoCancel", "OrderShipped", []string{"CancelOrder"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
			{
				Name:   "scheduleAutoCancel",
				Events: []string{"OrderPlaced"},
				Subs: []loom.SubscriptionDef{
					{Event: "OrderPlaced", Dispatches: []string{"CancelOrder"}},
				},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *OrderPlaced:
						cmds, err := impl.ScheduleAutoCancel.OnOrderPlaced(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("scheduleAutoCancel", "OrderPlaced", []string{"CancelOrder"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
		},
		Processes: []*loom.ReactorDef{
			{
				Name:   "shipOnPayment",
				Events: []string{"InvoicePaid"},
				Subs: []loom.SubscriptionDef{
					{Event: "InvoicePaid", Dispatches: []string{"ShipOrder"}},
				},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *InvoicePaid:
						cmds, err := impl.ShipOnPayment.OnInvoicePaid(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("shipOnPayment", "InvoicePaid", []string{"ShipOrder"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
		},
		Uploads: []*loom.UploadDef{
			{Name: "Contract", Owner: "Order", OnStarted: "RequestContract", StartedField: "contract", OnUploaded: "AttachContract", UploadedField: "contract"},
		},
		Joins: []*loom.JoinDef{
			{OnEntity: "CustomerSpend", Field: "orders", Service: "", Entity: "OrderSummary", List: true, Via: "customer_id"},
			{OnEntity: "CustomerSpend", Field: "invoices", Service: "billing", Entity: "InvoiceSummary", List: true, Via: "customer_id"},
		},
		Tables: []*loom.TableDef{
			{
				Entity: "OrderSummary",
				Name:   "loom_t_orders_order_summary",
				DDL: `CREATE TABLE IF NOT EXISTS loom_t_orders_order_summary (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"currency" text,
	"customer_id" uuid,
	"items" jsonb,
	"reason" text,
	"status" text,
	"total_cents" bigint,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);`,
				Columns: []loom.TableColumn{
					{Name: "currency", Type: "text"},
					{Name: "customer_id", Type: "uuid"},
					{Name: "items", Type: "jsonb"},
					{Name: "reason", Type: "text"},
					{Name: "status", Type: "text"},
					{Name: "total_cents", Type: "bigint"},
				},
				Values: func(state loom.EntityState) []any {
					e := state.(*OrderSummary)
					return []any{
						e.Currency,
						e.CustomerId,
						loom.JSONValue(e.Items),
						e.Reason,
						e.Status,
						e.TotalCents,
					}
				},
			},
		},
		Projections: []*loom.ProjectionDef{
			{
				Name:     "customerSpend",
				Entity:   "CustomerSpend",
				Events:   []string{"OrderPlaced"},
				NewState: func() loom.EntityState { return &CustomerSpend{} },
				EntityID: func(evt *loom.Event) uuid.UUID {
					switch e := evt.Data.(type) {
					case *OrderPlaced:
						return e.CustomerId
					}
					return evt.AggregateID
				},
				Fold: func(state loom.EntityState, evt *loom.Event) error {
					switch data := evt.Data.(type) {
					case *OrderPlaced:
						return impl.CustomerSpend.OnOrderPlaced(state.(*CustomerSpend), evt, data)
					}
					return fmt.Errorf("projection customerSpend: unroutable event %s", evt.Type)
				},
			},
			{
				Name:     "orderSummary",
				Entity:   "OrderSummary",
				Events:   []string{"OrderCancelled", "OrderPlaced", "OrderShipped"},
				NewState: func() loom.EntityState { return &OrderSummary{} },
				EntityID: func(evt *loom.Event) uuid.UUID { return evt.AggregateID },
			},
		},
	}
}

func asAny[T any](in []T) []any {
	out := make([]any, len(in))
	for i, v := range in {
		out[i] = v
	}
	return out
}

func checkDispatches(reactor, event string, allowed []string, cmds []loom.Command) error {
	for _, cmd := range cmds {
		ok := false
		for _, a := range allowed {
			if cmd.LoomCommand() == a {
				ok = true
				break
			}
		}
		if !ok {
			return fmt.Errorf("%s on %s dispatched undeclared command %s", reactor, event, cmd.LoomCommand())
		}
	}
	return nil
}
