// Code generated by loom generate. DO NOT EDIT.

package loomgen

import (
	"context"
	"fmt"

	"github.com/go-apis/loom"
	"github.com/google/uuid"
)

var _ = uuid.UUID{}

func loomErrNilEvent(eventType string) error {
	return fmt.Errorf("nil payload for event %s", eventType)
}

type OrderHandlers interface {
	CancelOrder(ctx context.Context, state *Order, cmd *CancelOrder) ([]loom.DomainEvent, error)
	PlaceOrder(ctx context.Context, state *Order, cmd *PlaceOrder) ([]loom.DomainEvent, error)
	ShipOrder(ctx context.Context, state *Order, cmd *ShipOrder) ([]loom.DomainEvent, error)
}

type ShipOnPaymentReactions interface {
	OnInvoicePaid(ctx context.Context, evt *loom.Event, data *InvoicePaid) ([]loom.Command, error)
}

type Impl struct {
	Order         OrderHandlers
	ShipOnPayment ShipOnPaymentReactions
}

func NewRegistry(impl Impl) *loom.Registry {
	return &loom.Registry{
		Service: "orders",
		Aggregates: []*loom.AggregateDef{
			{
				Name:          "Order",
				SnapshotEvery: 5,
				NewState:      func() loom.AggregateState { return &Order{} },
				Commands: []*loom.CommandDef{
					{
						Name:  "CancelOrder",
						New:   func() loom.Command { return &CancelOrder{} },
						Emits: []string{"OrderCancelled"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.CancelOrder(ctx, state.(*Order), cmd.(*CancelOrder))
							return asAny(evts), err
						},
					},
					{
						Name:  "PlaceOrder",
						New:   func() loom.Command { return &PlaceOrder{} },
						Emits: []string{"OrderPlaced"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.PlaceOrder(ctx, state.(*Order), cmd.(*PlaceOrder))
							return asAny(evts), err
						},
					},
					{
						Name:  "ShipOrder",
						New:   func() loom.Command { return &ShipOrder{} },
						Emits: []string{"OrderShipped"},
						Handle: func(ctx context.Context, state loom.AggregateState, cmd loom.Command) ([]any, error) {
							evts, err := impl.Order.ShipOrder(ctx, state.(*Order), cmd.(*ShipOrder))
							return asAny(evts), err
						},
					},
				},
			},
		},
		Events: []*loom.EventDef{
			{Name: "InvoicePaid", SchemaVersion: 1, Publish: true, Service: "billing", Aliases: nil, New: func() any { return &InvoicePaid{} }},
			{Name: "OrderCancelled", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &OrderCancelled{} }},
			{Name: "OrderPlaced", SchemaVersion: 1, Publish: true, Service: "", Aliases: nil, New: func() any { return &OrderPlaced{} }},
			{Name: "OrderShipped", SchemaVersion: 1, Publish: false, Service: "", Aliases: nil, New: func() any { return &OrderShipped{} }},
		},
		Policies: []*loom.ReactorDef{},
		Processes: []*loom.ReactorDef{
			{
				Name:   "shipOnPayment",
				Events: []string{"InvoicePaid"},
				React: func(ctx context.Context, evt *loom.Event) ([]loom.Command, error) {
					switch data := evt.Data.(type) {
					case *InvoicePaid:
						cmds, err := impl.ShipOnPayment.OnInvoicePaid(ctx, evt, data)
						if err != nil {
							return nil, err
						}
						return cmds, checkDispatches("shipOnPayment", "InvoicePaid", []string{"ShipOrder"}, cmds)
					}
					return nil, fmt.Errorf("unroutable event %s", evt.Type)
				},
			},
		},
		Projections: []*loom.ProjectionDef{
			{
				Name:     "orderSummary",
				Entity:   "OrderSummary",
				Events:   []string{"OrderCancelled", "OrderPlaced", "OrderShipped"},
				NewState: func() loom.EntityState { return &OrderSummary{} },
				EntityID: func(evt *loom.Event) uuid.UUID { return evt.AggregateID },
			},
		},
	}
}

func asAny[T any](in []T) []any {
	out := make([]any, len(in))
	for i, v := range in {
		out[i] = v
	}
	return out
}

func checkDispatches(reactor, event string, allowed []string, cmds []loom.Command) error {
	for _, cmd := range cmds {
		ok := false
		for _, a := range allowed {
			if cmd.LoomCommand() == a {
				ok = true
				break
			}
		}
		if !ok {
			return fmt.Errorf("%s on %s dispatched undeclared command %s", reactor, event, cmd.LoomCommand())
		}
	}
	return nil
}
