-- Code generated by loom generate. DO NOT EDIT.
--
-- Typed tables for @table entities/aggregates and series. Migrate
-- executes these and then applies an additive column diff; incompatible
-- drift is an error. @table remediation is drop table, Migrate, Rebuild;
-- series data is NOT rebuildable — incompatible series drift is migrated
-- by hand. On TimescaleDB, Migrate turns each series table into a
-- hypertable on its time column (with a retention policy for @retain);
-- on plain Postgres a @retain series is range-partitioned by day.

CREATE TABLE IF NOT EXISTS loom_t_orders_order_summary (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"currency" text,
	"customer_id" uuid,
	"items" jsonb,
	"reason" text,
	"status" text,
	"total_cents" bigint,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);

CREATE TABLE IF NOT EXISTS loom_s_orders_req_sample (
	service    text NOT NULL,
	namespace  text NOT NULL,
	"at" timestamptz NOT NULL,
	"duration_ms" double precision,
	"route" text NOT NULL,
	"sample_id" uuid NOT NULL,
	"status" bigint,
	PRIMARY KEY (service, namespace, "sample_id", "at")
);

-- @retain(30d): on plain Postgres Migrate creates the partitioned form instead and drops day partitions past retention;
-- on TimescaleDB it adds a retention policy to the hypertable.
CREATE TABLE IF NOT EXISTS loom_s_orders_req_sample (
	service    text NOT NULL,
	namespace  text NOT NULL,
	"at" timestamptz NOT NULL,
	"duration_ms" double precision,
	"route" text NOT NULL,
	"sample_id" uuid NOT NULL,
	"status" bigint,
	PRIMARY KEY (service, namespace, "sample_id", "at")
) PARTITION BY RANGE ("at");

CREATE TABLE IF NOT EXISTS loom_s_orders_sku_price (
	service    text NOT NULL,
	namespace  text NOT NULL,
	"note" text,
	"observed_at" timestamptz NOT NULL,
	"price_cents" bigint,
	"sku" text NOT NULL,
	"source" text NOT NULL,
	PRIMARY KEY (service, namespace, "sku", "source", "observed_at")
);

