-- Code generated by loom generate. DO NOT EDIT.
--
-- Typed tables for @table entities/aggregates and series. Migrate
-- executes these and then applies an additive column diff; incompatible
-- drift is an error. @table remediation is drop table, Migrate, Rebuild;
-- series data is NOT rebuildable — incompatible series drift is migrated
-- by hand. On TimescaleDB, Migrate turns each series table into a
-- hypertable on its time column.

CREATE TABLE IF NOT EXISTS loom_t_orders_order_summary (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"currency" text,
	"customer_id" uuid,
	"items" jsonb,
	"reason" text,
	"status" text,
	"total_cents" bigint,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);

CREATE TABLE IF NOT EXISTS loom_s_orders_sku_price (
	service    text NOT NULL,
	namespace  text NOT NULL,
	"note" text,
	"observed_at" timestamptz NOT NULL,
	"price_cents" bigint,
	"sku" text NOT NULL,
	"source" text NOT NULL,
	PRIMARY KEY (service, namespace, "sku", "source", "observed_at")
);

