-- Code generated by loom generate. DO NOT EDIT.
--
-- Typed tables for @table entities. Migrate executes these and then
-- applies an additive column diff; incompatible drift is an error, and
-- the remediation is drop table, Migrate, Rebuild.

CREATE TABLE IF NOT EXISTS loom_t_orders_order_summary (
	service    text NOT NULL,
	namespace  text NOT NULL,
	id         uuid NOT NULL,
	"currency" text,
	"customer_id" uuid,
	"items" jsonb,
	"reason" text,
	"status" text,
	"total_cents" bigint,
	updated_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (service, namespace, id)
);

